version: '3'

#todo not working with current envs
services:
  db:
    image: 'postgres:15.1-alpine3.17'
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  car-service:
    env_file:
      - .env
    build: .
    ports:
      - '8081:8080'
    container_name: car-service
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-data:
    driver: local
