version: '3'

services:
  db:
    env_file: .env
    restart: always
    image: 'postgres:latest'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    container_name: db

  car-service:
    env_file: .env
    build: .
    ports:
      - "8080:8080"
    container_name: car-service
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgresql-data:
    driver: local
