spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
  mapper-locations: classpath:db/mybatis/mapper/*.xml
  type-aliases-package: com.gznznzjsn.carservice.domain.carservice

springdoc:
  override-with-generic-response: false
  swagger-ui:
    path: /api/v1/docs

car-service:
  secrets:
    access-key: ${CAR-SERVICE_SECRETS_ACCESS-KEY}
    refresh-key: ${CAR-SERVICE_SECRETS_REFRESH-KEY}
