spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${POSTGRES_SCHEMA}

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
  mapper-locations: classpath:db/mybatis/mapper/*.xml
  type-aliases-package: com.gznznzjsn.carservice.domain.carservice

springdoc:
  override-with-generic-response: false
  swagger-ui:
    path: /api/v1/docs

car-service:
  secrets:
    access-key: ${JWT_ACCESS_KEY}
    refresh-key: ${JWT_REFRESH_KEY}
