spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/car_service
    username: postgres
    password: 1q2w3e
  jpa:
    hibernate:
      ddl-auto: create-drop
